/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "meqlnalcrtnfamkhsbcp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lcWxuYWxjcnRuZmFta2hzYmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MDI4MjUsImV4cCI6MjA3NjA3ODgyNX0.F-cFT3pdWg7X8Ih97KNLvrrxMt894jXuM5VWF-UoLRg"